name: Test Windows arm64

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Install InnoSetup
        shell: pwsh
        run: |
          choco install innosetup      
          
      - name: Test CURL
        shell: bash
        run: |
          curl -o out.json \
            --url https://api.github.com/repos/artpixls/ART-imageio/releases \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
          echo "GOT JSON:"
          cat out.json

      - name: Test urlopen
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python --version
          python repo/test_urlopen.py
