name: Test

on:
  push:
    branches:
      - releases
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:

      - uses: olegtarasov/get-tag@v2.1.3
        id: tagName
        with:
          tagRegex: "v.*"
      
      - name: Check github ref
        run: |
          echo "GITHUB_REF = <${GITHUB_REF}>"
          echo "GITHUB_REF_TYPE = <${GITHUB_REF_TYPE}>"
          echo "GITHUB_REF_NAME = <${GITHUB_REF_NAME}>"
          echo "GIT_TAG_NAME = <${GIT_TAG_NAME}>"
