name: Test Windows arm64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm

    permissions:
      contents: write

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          location: C:\msys2
          update: true
          msystem: CLANGARM64
          install: |
            git
            wget
            xz
            p7zip

      - name: Download pkgs
        run: |
          mkdir repo-clangarm64
          for p in adwaita-icon-theme-48.0-1 adwaita-icon-theme-legacy-46.2-1 atk-2.56.2-1 atkmm-2.28.4-1 autotools-2023.09.28-2 brotli-1.1.0-5 bzip2-1.0.8-3 c-ares-1.34.5-1 ca-certificates-20241223-1 cairo-1.18.4-2 cairomm-1.14.5-2 clang-20.1.5-2 clang-libs-20.1.5-2 cmake-4.0.2-1 compiler-rt-20.1.5-2 cppdap-1.65-1 crt-git-13.0.0.r1.gb45abfec4-1 curl-8.14.1-1 egl-headers-1.5.r255.9ab6036-1 expat-2.7.1-2 fftw-3.3.10-5 fontconfig-2.16.2-1 freeglut-3.6.0-1 freetype-2.13.3-1 fribidi-1.0.16-1 gdk-pixbuf2-2.42.12-4 gettext-libtextstyle-0.25-1 gettext-runtime-0.25-1 gettext-tools-0.25-1 giflib-5.2.2-1 gles-headers-3.2.r1005.d127c30-1 glew-2.2.0-3 glib2-2.84.2-1 glibmm-2.66.8-1 gmp-6.3.0-2 gnutls-3.8.9-4 graphite2-1.3.14-3 gtk-update-icon-cache-3.24.49-1 gtk3-3.24.49-1 gtkmm3-3.24.10-2 harfbuzz-11.2.1-1 headers-git-13.0.0.r1.gb45abfec4-1 hicolor-icon-theme-0.18-1 imath-3.1.12-2 jbigkit-2.1-5 json-glib-1.10.6-1 jsoncpp-1.9.6-3 lcms2-2.17-1 lensfun-0.3.4-3 lerc-4.0.0-1 libarchive-3.8.1-2 libb2-0.98.1-2 libc++-20.1.5-2 libdatrie-0.2.13-3 libdeflate-1.24-1 libepoxy-1.5.10-5 libffi-3.5.0-1 libiconv-1.18-1 libidn2-2.3.8-2 libjpeg-turbo-3.1.0-1 libltdl-2.5.4-1 libpng-1.6.48-1 libpsl-0.21.5-3 librsvg-2.60.0-1 libsigc++-2.12.1-1 libssh2-1.11.1-1 libsystre-1.0.2-1 libtasn1-4.20.0-1 libthai-0.1.29-3 libtiff-4.7.0-1 libtool-2.5.4-1 libtre-0.9.0-1 libunistring-1.3-1 libunwind-20.1.5-2 libuv-1.51.0-1 libwebp-1.5.0-1 libwinpthread-13.0.0.r1.gb45abfec4-1 libxml2-2.12.10-1 lld-20.1.5-2 llvm-libs-20.1.5-2 llvm-openmp-20.1.5-1 llvm-tools-20.1.5-2 lz4-1.10.0-1 lzo2-2.10-2 mimalloc-2.2.2-4 minizip-ng-4.0.10-1 mpdecimal-4.0.1-1 ncurses-6.5.20241228-3 nettle-3.10.1-1 nghttp2-1.65.0-1 nghttp3-1.10.1-1 ngtcp2-1.13.0-2 ninja-1.12.1-2 opencolorio-2.4.2-3 openexr-3.3.4-1 openssl-3.5.0-1 p11-kit-0.25.5-1 pango-1.56.3-2 pangomm-2.46.4-1 pcre2-10.45-1 pixman-0.46.2-1 pkgconf-1~2.4.3-1 python-3.12.11-1 python-packaging-25.0-1 readline-8.2.013-1 rhash-1.4.5-1 shared-mime-info-2.4-1 sqlite3-3.50.1-1 tcl-8.6.16-1 termcap-1.3.1-7 tk-8.6.16-1 tzdata-2025b-1 wineditline-2.208-1 winpthreads-13.0.0.r1.gb45abfec4-1 xz-5.8.1-2 yaml-cpp-0.8.0-1 zlib-1.3.1-1 zstd-1.5.7-1; do
            cd repo-clangarm64
            pkg=mingw-w64-clang-aarch64-${p}-any.pkg.tar.zst
            wget https://repo.msys2.org/mingw/clangarm64/${pkg}
            cd ..
            repo-add ./repo-clangarm64/custom-clangarm64.db.tar.zst ./repo-clangarm64/${pkg}
          done
          echo "CUSTOM_REPO_DIR=${PWD}/repo-clangarm64" >> "$(cygpath -u $GITHUB_ENV)"

      - name: Setup local repo
        run: |
          echo "[options]" > /etc/pacman.conf
          echo "HoldPkg     = pacman" >> /etc/pacman.conf
          echo "Architecture = auto" >> /etc/pacman.conf
          echo "SigLevel    = Required" >> /etc/pacman.conf
          echo "LocalFileSigLevel = Optional" >> /etc/pacman.conf
          echo "[msys]" >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/mirrorlist.msys" >> /etc/pacman.conf
          echo "[custom-clangarm64]" >> /etc/pacman.conf
          echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf
          echo "Server = file://${CUSTOM_REPO_DIR}" >> /etc/pacman.conf

      - name: Install local pkgs
        run: |
          pacman -Sy
          for p in clang cmake autotools ninja gtkmm3 lcms2 fftw lensfun mimalloc opencolorio; do
              pacman --noconfirm -S custom-clangarm64/mingw-w64-clang-aarch64-${p}
          done

      - name: Prepare artifact
        run: |
          tar cf repo-clangarm64.tar repo-clangarm64

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: clangarm64
          body: clangarm64
          allowUpdates: true
          makeLatest: true
          artifacts: repo-clangarm64.tar
