name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-14

    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo

      - if: false
        name: Install MacPorts arm64
        run: |          
          wget https://github.com/macports/macports-base/releases/download/v2.10.4/MacPorts-2.10.4-14-Sonoma.pkg
          sudo installer -pkg MacPorts-2.10.4-14-Sonoma.pkg -target /
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          
      - if: false
        name: Install base ports
        run: |          
          export PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:$PATH
          sudo port install pkgconfig
          sudo port install automake
          sudo port install autoconf
          sudo port install libtool
          sudo port install cmake
          sudo port install glib2 +quartz
          sudo port install gtkmm3 +quartz
          sudo port install gtk-osx-application-gtk3
          sudo port install libomp
          sudo port install clang-17
          sudo port install librsvg-devel
          sudo port install lensfun
          sudo port install exiv2
          sudo port install fftw-3-single +openmp
          sudo port install openexr
          sudo port install lcms2
          sudo port install adwaita-icon-theme
          sudo port install meson
          sudo port install dbus

      - if: ${{ vars.CURL == 'true' && vars.RUN == 'true' }}
        name: Test CURL
        run: |
          curl -o out.json https://api.github.com/repos/artpixls/ART-imageio/releases
          echo "GOT JSON:"
          cat out.json

      - name: Test urlopen
        run: |
          /usr/bin/python3 --version
          /usr/bin/python3 repo/test_urlopen.py
